#!/usr/bin/env bash
# Install a per-user LaunchAgent that unlocks the permanent signing keychain at
# login, so `codesign` works after every reboot without a manual unlock.
#
# The keychain password is written to a mode-700 file under ~/.config/palmr
# (NOT committed). Override the default with SIGNING_KC_PW.
#
#   SIGNING_KC_PW=palmr scripts/install-signing-keychain-launchagent.sh
set -euo pipefail

KC="$HOME/Library/Keychains/palmr-signing.keychain-db"
PW="${SIGNING_KC_PW:-palmr}"
DIR="$HOME/.config/palmr"
UNLOCK="$DIR/unlock-signing-keychain.sh"
LABEL="ai.palmr.signing-keychain-unlock"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"

mkdir -p "$DIR" "$HOME/Library/LaunchAgents"

cat > "$UNLOCK" <<EOF
#!/bin/bash
# Auto-generated by install-signing-keychain-launchagent.sh — do not commit.
security unlock-keychain -p '$PW' "$KC"
EOF
chmod 700 "$UNLOCK"

cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>$LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$UNLOCK</string>
    </array>
    <key>RunAtLoad</key><true/>
</dict>
</plist>
EOF
chmod 600 "$PLIST"

launchctl unload "$PLIST" 2>/dev/null || true
launchctl load -w "$PLIST"
echo "✓ Installed LaunchAgent $LABEL (unlocks $KC at login)."
